version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sifre123
      POSTGRES_DB: okullar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-postgres-network
    ports:
      - "5432:5432"

    command: ["postgres", "-c", "logging_collector=on", "-c", "log_destination=stderr", "-c", "log_directory=/var/lib/postgresql/data/logs", "-c", "log_filename=postgresql.log"]
  springboot-app:
    image: yks_siralama_web
    container_name: yks_siralama_web_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring-postgres-network
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/okullar
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: sifre123
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
    links:
      - postgres

volumes:
  postgres_data:
networks:
  spring-postgres-network: